llm:
  provider: GEMINI
  meta:
    model: gemini-2.0-pro
    max_tokens: 1200
    temperature: 0.3
  http_client:
    api_url: https://generativelanguage.googleapis.com
    api_token: ${LLM__HTTP_CLIENT__API_TOKEN}

vcs:
  provider: GITHUB
  pipeline:
    owner: ${VCS__PIPELINE__OWNER}
    repo: ${VCS__PIPELINE__REPO}
    pull_number: ${VCS__PIPELINE__PULL_NUMBER}
  http_client:
    api_url: https://api.github.com
    api_token: ${VCS__HTTP_CLIENT__API_TOKEN}

core:
  concurrency: 7

review:
  mode: FULL_FILE_DIFF
  dry_run: true
  max_inline_comments: 50

prompt:
  inline_prompt_files: [ ./prompts/inline.md ]
  context_prompt_files: [ ./prompts/inline.md ]
  summary_prompt_files: [ ./prompts/summary.md ]

logger:
  level: INFO